apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust-instance
  template:
    metadata:
      labels:
        name: locust-instance
    spec:
      containers:
        - name: locust-instance
          image: image-registry.openshift-image-registry.svc:5000/flask-backend/flask-server:latest
          command:
            - "bash"
            - "-c"
            - "locust -f locustfile.py --host=http://flask-server:8080"
