kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: locust
  namespace: locust
  labels:
    name: locust-instance
spec:
  host: locust-locust.apps.cluster1.tide.lan
  to:
    kind: Service
    name: locust
    weight: 100
  port:
    targetPort: 8089
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None