apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rabbitmq-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        metricName: celery_messages_unacknowledged
        target:
          kind: Namespace
          name: rabbitmq
        targetValue: "10"
