apiVersion: v1
data:
  Dockerfile: |
    FROM scratch
    LABEL description="This is a Custom ContainerDisk for Celery VM's"
    LABEL maintainer="https://github.com/MoOyeg"
    LABEL url="https://github.com/MoOyeg/flask-celery-microservice?tab=readme-ov-file#building-celery-vmsoptional"
    ADD --chown=107:107 disk.img /disk/
kind: ConfigMap
metadata:
  name: dockerfile
  namespace: celery-workers