kind: ConfigMap
apiVersion: v1
metadata:
  name: celery-install-script
  namespace: celery-workers
immutable: false
data:
  celery-install-script.sh: |-
    #/bin/sh

    mkdir flask-celery-microservice
    git clone https://github.com/MoOyeg/flask-celery-microservice.git flask-celery-microservice
    pip install -r ./flask-celery-microservice/flask-server-app/requirements.txt
