apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: celery-custom-build
  namespace: celery-workers
spec:
  params:
    - description: The OpenShift object to check for
      name: OBJECT_NAME
      type: string
    - description: The Object Type to check for
      name: OBJECT_TYPE
      type: string
    - description: The PVC that virt-customize will act on
      name: PVC
      type: string
    - description: OUTPUT ContainerDisk IMAGE
      name: IMAGE
      type: string
    - description: GIT Url to clone
      name: URL
      type: string
    - description: GIT Revision to checkout 
      name: REVISION
      type: string
    - description: GIT Repo Name
      name: REPO_NAME
      type: string
  tasks:
    - name: oc-wait-until-object-deleted
      params:
        - name: OBJECT_NAME
          value: $(params.OBJECT_NAME)
        - name: OBJECT_TYPE
          value: $(params.OBJECT_TYPE)
        - name: SLEEP_TIMER
          value: '5'
        - name: VERSION
          value: '4.12'
      taskRef:
        kind: Task
        name: oc-wait-until-object-deleted
    - name: git-clone-repository
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.URL)
        - name: revision
          value: $(params.REVISION))        
      taskRef:
        kind: Task
        name: git-clone
      runAfter:
        - oc-wait-until-object-deleted
    - name: disk-virt-customize
      workspaces:
        - name: data01
          workspace: data01
        - name: data02
          workspace: data02
        - name: output
          workspace: output
      params:
        - name: pvc
          value: $(params.PVC)
        - name: repo_name
          value: $(params.REPO_NAME)
        - name: customizeCommands
          value: |
            update
            install git,python3,python3-pip
            upload /output/$(params.REPO_NAME):/root/$(params.REPO_NAME)
            run pip3 install -r /root/$(params.REPO_NAME)/flask-server-app/requirements.txt
            firstboot /root/$(params.REPO_NAME)/celery-vm-workers/build-image/celery-entrypoint-script.sh
            delete /var/cache/dnf
        - name: verbose
          value: 'false'
        - name: additionalOptions
          value: ''
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: disk-virt-customize
    - name: build-containerdisk
      workspaces:
        - name: source
          workspace: source
      params:
        - name: pvc
          value: $(params.PVC)
        - name: IMAGE
          value: $(params.IMAGE)        
      taskRef:
        kind: Task
        name: buildah-containerdisk-as-user
      runAfter:
        - disk-virt-customize
  workspaces:
    - name: data01 
    - name: data02
    - name: source
    - name: output
    

