kind: ConfigMap
apiVersion: v1
metadata:
  name: celery-entrypoint-script
  namespace: celery-workers
immutable: false
data:
  celery-entrypoint-script.sh: |-
    #/bin/bash
    celery -A main.celery worker -l info

