apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: celery-workers-pool
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vm: celery-workers-pool
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vm: celery-workers-pool
    spec:
      dataVolumeTemplates:
      - metadata:
          creationTimestamp: null
          name: celery-worker-dv
        spec:
          pvc:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: $STORAGECLASS_NAME
          source:
            pvc:
              name: custom-celery-dv
              namespace: celery-workers
      running: true
      template:
        metadata:
          labels:
            kubevirt.io/vm: celery-workers-pool
        spec:
          domain:
            cpu:
              cores: 1
              model: host-model
              sockets: 1
              threads: 1
            devices:
              disks:
              - disk:
                  bus: virtio
                name: rootdisk
              - disk:
                  bus: virtio
                name: cloudinitdisk            
            features:
              acpi:
                enabled: true
            machine:
              type: pc-q35-rhel9.2.0
            resources:
              requests:
                memory: 2Gi
          terminationGracePeriodSeconds: 0
          volumes:
            - dataVolume:
                name: celery-worker-dv
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: centos
                  password: 3g47-yxhg-ob2r
                  chpasswd: { expire: False }
                  runcmd:
                    - celery -A main.celery worker -l info
              name: cloudinitdisk




apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    vm.kubevirt.io/flavor: small
    vm.kubevirt.io/os: centos-stream8
    vm.kubevirt.io/workload: server
  name: centos-stream8-divine-test
  namespace: celery-workers
  labels:
    kubevirt.io/domain: centos-stream8-divine-test
    kubevirt.io/nodeName: worker3
    kubevirt.io/size: small
spec:
  domain:
    cpu:
      cores: 1
      model: host-model
      sockets: 1
      threads: 1
    devices:
      disks:
        - disk:
            bus: virtio
          name: rootdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - masquerade: {}
          model: virtio
          name: default
      networkInterfaceMultiqueue: true
      rng: {}
    features:
      acpi:
        enabled: true
    machine:
      type: pc-q35-rhel9.2.0
    resources:
      requests:
        memory: 2Gi
  evictionStrategy: LiveMigrate
  networks:
    - name: default
      pod: {}
  terminationGracePeriodSeconds: 180
  volumes:
    - dataVolume:
        name: custom-celery-dv
      name: rootdisk
    - cloudInitNoCloud:
        userData: |-
          #cloud-config
          user: centos
          password: 3g47-yxhg-ob2r
          chpasswd: { expire: False }
      name: cloudinitdisk