kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/MoOyeg/flask-celery-microservice.git'
  name: custom-autoscale-app
  namespace: celery-workers
  labels:
    name: custom-autoscale-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "custom-autoscale-app:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/MoOyeg/flask-celery-microservice.git'
    contextDir: /ocp_virt_autoscale_app/app-manifest
  triggers:
    - type: ConfigChange
  runPolicy: Serial