apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-vm-autoscale-app
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "kubevirt.io"
  resources:
  - virtualmachines
  - virtualmachineinstances
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch

