apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-vm-autoscale-app-rolebinding 
  namespace: celery-workers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-vm-autoscale-app
subjects:
- kind: ServiceAccount
  name: custom-vm-autoscale-app-sa 
  namespace: celery-workers
