apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thanos-metrics-reader
  namespace: celery-workers
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - VirtualMachine
  - VirtualMachineInstance
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  - VirtualMachine
  - VirtualMachineInstance
  verbs:
  - get
  - list
  - watch