apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-metrics-reader 
  namespace: celery-workers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-metrics-reader
subjects:
  - kind: ServiceAccount
    name: thanos 
    namespace: celery-workers
