kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    name: rabbitmq-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "rabbitmq:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "rabbitmq:3.8-management"
  postCommit: {}
  source:
    type: Git
    contextDir: /rabbitmq
    git:
      uri: "https://github.com/MoOyeg/flask-celery-microservice.git"
  runPolicy: Serial