# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8-management
        envFrom:
            - secretRef:
                name: rabbitmq-secret
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq