kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/MoOyeg/flask-celery-microservice.git'
  name: flask-server
  namespace: flask-backend
  labels:
    name: flask-server-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "flask-server:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/MoOyeg/flask-celery-microservice.git'
    contextDir: /flask-server-app
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8
  runPolicy: Serial