apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: celery-workers-pool
  namespace: celery-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      kubevirt.io/vm: celery-workers-pool
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vm: celery-workers-pool
    spec:
      running: true
      template:
        metadata:
          labels:
            kubevirt.io/vm: celery-workers-pool
        spec:
          domain:
            cpu:
              cores: 1
              model: host-model
              sockets: 1
              threads: 1
            devices:
              disks:
              - disk:
                  bus: virtio
                name: containerdisk
              - disk:
                  bus: virtio
                name: cloudinitdisk
              - disk:
                  bus: virtio
                name: environment-disk-celerysecret
              serial: CELERYSECRET          
            features:
              acpi:
                enabled: true
            machine:
              type: pc-q35-rhel9.2.0
            resources:
              requests:
                memory: 2Gi
          terminationGracePeriodSeconds: 0
          volumes:
            - containerDisk:
                image: quay.io/mooyeg/containerdisk-celery:v1.0
              name: containerdisk
            - name: environment-disk-celerysecret
              secret:
                secretName: celery-workers-secret
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: centos
                  password: centos
                  chpasswd: { expire: False }
              name: cloudinitdisk
