apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: celery-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      name: celery-worker
  template:
    metadata:
      labels:
        name: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: image-registry.openshift-image-registry.svc:5000/flask-backend/flask-server:latest
          command:
            - "bash"
            - "-c"
            - "celery -A main.celery worker -l info"
          envFrom:
            - secretRef:
                name: celery-workers-secret
          resources:
            limits:
              cpu: 200m
              memory: 750Mi
            requests:
              cpu: 200m
              memory: 750Mi