kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:image-pullers:celery-workers'
  namespace: flask-backend
  annotations:
    openshift.io/description: >-
      Allows all pods in the celery-workers namespace to pull from flask-backend namespace
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:celery-workers'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
